### ISSUE TITLE
Sonar-erlang verion 1.4 is not compatible with sonarqube developer version 9.6

### ISSUE THREAD

**Issue by sisihlia** [SonarCommunity/sonar-erlang#58]
Hello

I am trying to work with sonar-erlang version 1.4 The version of sonarqube installed is developer 9.6. I’ve downloaded the jar and put it in $SONARQUBE_HOME/extensions/plugins. But the sonarqube failed to start as below error

sonarqube-sonarqube-1  | 2022.08.17 13:46:02 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
sonarqube-sonarqube-1  | java.lang.IllegalStateException: Fail to load plugin Erlang [erlang]
sonarqube-sonarqube-1  |        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:81)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:645)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:196)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:177)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:105)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:344)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:105)
sonarqube-sonarqube-1  |        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:328)
sonarqube-sonarqube-1  |        at java.base/java.lang.Thread.run(Thread.java:829)
sonarqube-sonarqube-1  | Caused by: java.lang.NoClassDefFoundError: org/sonar/api/profiles/ProfileDefinition
sonarqube-sonarqube-1  |        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
sonarqube-sonarqube-1  |        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
sonarqube-sonarqube-1  |        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
sonarqube-sonarqube-1  |        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
sonarqube-sonarqube-1  |        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
sonarqube-sonarqube-1  |        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
sonarqube-sonarqube-1  |        at java.base/java.security.AccessController.doPrivileged(Native Method)
sonarqube-sonarqube-1  |        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
sonarqube-sonarqube-1  |        at org.sonar.plugins.erlang.ErlangPlugin.define(ErlangPlugin.java:100)
sonarqube-sonarqube-1  |        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:71)
sonarqube-sonarqube-1  |        ... 8 common frames omitted
sonarqube-sonarqube-1  | Caused by: java.lang.ClassNotFoundException: org.sonar.api.profiles.ProfileDefinition
sonarqube-sonarqube-1  |        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
sonarqube-sonarqube-1  |        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
sonarqube-sonarqube-1  |        ... 22 common frames omitted
sonarqube-sonarqube-1  | 2022.08.17 13:46:02 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
sonarqube-sonarqube-1  | 2022.08.17 13:46:03 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped
sonarqube-sonarqube-1  | 2022.08.17 13:46:03 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
sonarqube-sonarqube-1  | 2022.08.17 13:46:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
sonarqube-sonarqube-1  | 2022.08.17 13:46:03 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

Is there compatibility issue it is stated that the plugin has been tested to work with SonarQube Community Version 8.9.0 ?
